shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux new-session -A -s main"
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 11
  use_thin_strokes: false
window:
  startup_mode: Maximized
