name: dotfiles deploy

on:
 schedule:
   - cron: '0 18 * * *'
 workflow_dispatch:


jobs:
  dotfiles:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y rename
      - uses: actions/checkout@v3
        with:
          path: 'repo'
      - uses: actions/checkout@v3
        with:
          repository: l3d00m/dotfiles
          ref: refs/heads/main
          path: 'orig_dotfiles'
      - name: Copy files
        run: |
          cp -r orig_dotfiles/dot** .
          cp -r orig_dotfiles/private_dot** .
          cp -r repo/.git .
          cp -r repo/.github .
          cp orig_dotfiles/*.sh .
          rename 's/^(private_)?dot_/./' *
          rm -r orig_dotfiles repo
      - uses: EndBug/add-and-commit@v9
